name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    name: ${{ matrix.friendlyName }}
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10
    strategy:
      fail-fast: false
      matrix:
        node: [12.14.1]
        os: [macos-latest, windows-latest, ubuntu-latest]
        include:
          - os: macos-latest
            friendlyName: macOS
          - os: windows-latest
            friendlyName: Windows
          - os: ubuntu-latest
            friendlyName: Linux
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Use Node.js ${{ matrix.node }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - name: Install and build
        run: yarn
      - name: Lint
        run: yarn lint
      - name: Test
        run: yarn test
        shell: bash
      - name: Prebuild Node x64
        run: yarn prebuild-node
      - name: Prebuild Node x86
        run: yarn prebuild-node-ia32
      - name: Prebuild Electron x64
        run: yarn prebuild-electron
      - name: Prebuild Electron x86
        run: yarn prebuild-electron-ia32
      - name: Prebuild Electron arm64
        run: yarn prebuild-electron-arm64
      - name: Publish
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
        run: yarn upload
        env:
          GITHUB_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
