name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    name: ${{ matrix.friendlyName }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        node: [12.14.1]
        os: [macos-10.15, windows-2019]
        include:
          - os: macos-10.15
            friendlyName: macOS
          - os: windows-2019
            friendlyName: Windows
    timeout-minutes: 45
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Use Node.js ${{ matrix.node }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - name: Install and build
        run: yarn
